#!/bin/bash
IMAGE_PATH="/tmp"
SCROT_NAME="$IMAGE_PATH/i3_screenshot.png"

# Take screenshot
scrot $SCROT_NAME

# Blur background
convert $SCROT_NAME -blur 0x8 $SCROT_NAME

# Add image
convert -composite $SCROT_NAME $HOME/.config/i3/dwight.png -gravity South -geometry -20x1200 $SCROT_NAME

# Lock screen
i3lock -i $SCROT_NAME
